(function(){var ov=document.getElementById('menuOverlay');function open(){ov.classList.add('open');}
function close(){ov.classList.remove('open');}
['menuOpen','menuOpen2'].forEach(function(id){var el=document.getElementById(id);if(el)el.addEventListener('click',open);});document.getElementById('menuClose').addEventListener('click',close);})();(function(){var sm=document.getElementById('stampModal');if(!sm)return;function open(){sm.classList.add('open');}
function close(){sm.classList.remove('open');}
document.getElementById('smClose').addEventListener('click',close);sm.addEventListener('click',function(e){if(e.target===sm)close();});var trig=document.getElementById('openStamp');if(trig)trig.addEventListener('click',function(e){e.preventDefault();open();});setTimeout(open,3000);})();(function(){var pill=document.getElementById('coinPill'),menu=document.getElementById('coinMenu');if(!pill||!menu)return;pill.addEventListener('click',function(e){e.stopPropagation();menu.classList.toggle('open');});document.addEventListener('click',function(e){if(!menu.contains(e.target)&&!pill.contains(e.target))menu.classList.remove('open');});})();(function(){var m=document.getElementById('profileModal'),openBtn=document.getElementById('profileOpen');if(!m||!openBtn)return;function open(){m.classList.add('open');}
function close(){m.classList.remove('open');}
openBtn.addEventListener('click',open);var op2=document.getElementById('openProfile2');if(op2)op2.addEventListener('click',function(e){e.preventDefault();var ov=document.getElementById('menuOverlay');if(ov)ov.classList.remove('open');open();});document.getElementById('pmClose').addEventListener('click',close);m.addEventListener('click',function(e){if(e.target===m)close();});document.getElementById('pmAvatarInput').addEventListener('change',function(e){var f=e.target.files[0];if(!f)return;document.getElementById('pmAvatarImg').src=URL.createObjectURL(f);});document.getElementById('pmSave').addEventListener('click',function(){var name=(document.getElementById('pmName').value||'').trim()||'かなぽん';document.querySelectorAll('[data-ms-member="first-name"]').forEach(function(el){if(el.tagName!=='INPUT')el.textContent=name;else el.value=name;});var src=document.getElementById('pmAvatarImg').src;document.querySelectorAll('.ss-avatar img, .member-avatar img').forEach(function(im){im.src=src;});close();});})();
var coinBalance=2800;function setCoin(n,animate){var el=document.querySelector('.coin-num');if(!animate||matchMedia('(prefers-reduced-motion: reduce)').matches){el.textContent=n.toLocaleString();document.querySelector('.coin-yen').textContent=n.toLocaleString()+'円分';return;}
var from=coinBalance===n?0:coinBalance,t0=null,dur=900;function step(t){if(!t0)t0=t;var p=Math.min((t-t0)/dur,1);p=1-Math.pow(1-p,3);var v=Math.round(from+(n-from)*p);el.textContent=v.toLocaleString();if(p<1)requestAnimationFrame(step);else document.querySelector('.coin-yen').textContent=n.toLocaleString()+'円分';}
requestAnimationFrame(step);}
(function(){var t=coinBalance;coinBalance=0;setTimeout(function(){setCoin(t,true);coinBalance=t;},2300);})();(function(){var w=document.getElementById('welcome');if(matchMedia('(prefers-reduced-motion: reduce)').matches){w.remove();return;}
setTimeout(function(){w.classList.add('open');},1400);setTimeout(function(){w.remove();},2700);})();(function(){var targets=document.querySelectorAll('.earn-row,.result-card,.referral-banner,.rank-card,.line-banner,.mile-card');targets.forEach(function(t){t.classList.add('reveal');});var io=new IntersectionObserver(function(entries){entries.forEach(function(e){if(e.isIntersecting){e.target.classList.add('in');io.unobserve(e.target);}});},{threshold:.12});targets.forEach(function(t){io.observe(t);});})();
/* マイルランキング: ユーザー名が未設定なら「名前を決める」を表示 */
(function(){var nameEl=document.querySelector('#mileMeCard [data-ms-member="first-name"]');var meCard=document.getElementById('mileMeCard');var prompt=document.getElementById('mileNamePrompt');if(!meCard||!prompt)return;function refresh(){var v=nameEl?(nameEl.textContent||'').trim():'';var empty=!v;prompt.style.display=empty?'flex':'none';meCard.style.display=empty?'none':'flex';}refresh();prompt.addEventListener('click',function(e){e.preventDefault();var m=document.getElementById('profileModal');if(m)m.classList.add('open');});})();